### ISSUE TITLE
Flavor type issue

### ISSUE THREAD

**Issue by JackCA** [kuzalekon/type-brandy#1]
When `Flavor`, it [appears that the example in the README doesn't work](https://codesandbox.io/s/pensive-christian-3tmw06?file=/src/index.ts)

<img width="639" alt="CleanShot 2022-07-28 at 12 41 14@2x" src="https://user-images.githubusercontent.com/296167/181623592-73298f3a-e488-42cf-8d37-2130330b19f0.png">

**Comment by kuzalekon** [comment]
Hi, @JackCA!
Thank You for the report. I fixed `Flavor` type definition in [v1.0.2](https://github.com/zalekkuz/ts-branding/tree/v1.0.2).

**Comment by JackCA** [comment]
@kalexey89 nice!!
