### ISSUE TITLE
ts-branding package on npm is disappeared

### ISSUE THREAD

**Issue by fengkx** [kuzalekon/type-brandy#2]
Everything in CI is break. You can deprecated the old package and use a new name, But deleteing a package that already existed for several months is not a good idea.

**Comment by kuzalekon** [comment]
Hi @fengkx!
I'm really sorry. Decided to delete it because npmjs.com showed that there are no packages that depend on `ts-branding`.

**Comment by fengkx** [comment]
npm only show dependencies but not devDependencies.
